apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-demo
  namespace: {{ .Release.Namespace }}
  labels:
    app: flask-demo
    env: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: flask-demo
    env: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP